### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/gdrive/My Drive/CARL/RUNS2/06_21_9x9'

### ISSUE THREAD

**Issue by chauncygu** [elbecerrasoto/CARL#1]
when I run the colab dqn, I met the problem:FileNotFoundError: [Errno 2] No such file or directory: '/gdrive/My Drive/CARL/RUNS2/06_21_9x9', could you help me fix it?

**Comment by elbecerrasoto** [comment]
Not fixing.
